### ISSUE TITLE
Windows 10 Release Preview build 19041.3513 need support

### ISSUE THREAD

**Issue by qaz1qazlol2** [stascorp/rdpwrap#2344]
here are the files and screenshot
![RDP Wrapper Configuration and Check utility by sebaxakerhtc 2023_9_26 10_23_10](https://github.com/stascorp/rdpwrap/assets/115929847/219a668c-ba2c-49c3-9193-fe20a8b727b5)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12721351/termsrv.zip)

**Comment by sashaqwert** [comment]
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/ba25392dacc9012bca8bdec608d9f9e0b3627f30

**Comment by qaz1qazlol2** [comment]
fixed,thanks
![1](https://github.com/stascorp/rdpwrap/assets/115929847/bcfee980-e076-4ecf-a018-5a0ed7ca0c10)

**Comment by andr0med** [comment]
Hi guys, mine was Not Listening and Not Supported.  After I applied the .ini from above, it fixed half of the problem but it's still Not Listening.  I tried stopping and restarting term service but no luck.  Thanks!
![image](https://github.com/stascorp/rdpwrap/assets/32721517/d1311ce7-d147-4bce-9e29-1b9da55d8dd9)

**Comment by penacg** [comment]
Hi guys, I need suport to ver: 10.0.19041.35.16 (Windows 10)
![image](https://github.com/stascorp/rdpwrap/assets/46824043/f3899990-07e2-4b72-ba0f-862d104bbaa2)

**Comment by sashaqwert** [comment]
@penacg Your version is offtopic in this thread. Please, use search in issues.

If you can't find, then you can create a new issue.
