### ISSUE TITLE
Add support for build 10.0.17763.292

### ISSUE THREAD

**Issue by RoosterIllusion** [stascorp/rdpwrap#645]
I am currently able to login by using the same offsets as 288 from here: https://github.com/stascorp/rdpwrap/issues/638#issuecomment-453824256

I have only tested x64.

`;
;----------------------snip part1
[10.0.17763.292]
; Patch CEnforcementCore::GetInstanceOfTSLicense
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=AFAD4
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=77A11
LocalOnlyCode.x64=jmpshort
; Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
SingleUserPatch.x86=1
SingleUserOffset.x86=4D665
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=1322C
SingleUserCode.x64=Zero
; Patch CDefPolicy::Query
DefPolicyPatch.x86=1
DefPolicyOffset.x86=4BE69
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17F45
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
; Hook CSLQuery::Initialize
SLInitHook.x86=1
SLInitOffset.x86=5B18A
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=1ABFC
SLInitFunc.x64=New_CSLQuery_Initialize
;.------------------------------------
;

;
;.--------------------------snip part2
[10.0.17763.292-SLInit]
bInitialized.x86 =CD798
bServerSku.x86 =CD79C
lMaxUserSessions.x86 =CD7A0
bAppServerAllowed.x86 =CD7A8
bRemoteConnAllowed.x86=CD7AC
bMultimonAllowed.x86 =CD7B0
ulMaxDebugSessions.x86=CD7B4
bFUSEnabled.x86 =CD7B8

bInitialized.x64 =ECAB0
bServerSku.x64 =ECAB4
lMaxUserSessions.x64 =ECAB8
bAppServerAllowed.x64 =ECAC0
bRemoteConnAllowed.x64=ECAC4
bMultimonAllowed.x64 =ECAC8
ulMaxDebugSessions.x64=ECACC
bFUSEnabled.x64 =ECAD0
;.---------------------------
;`

**Comment by binarymaster** [comment]
> 10.0.17763.292

@RoosterIllusion could you proof this build really exists? Post RDPConf screenshot.

**Comment by RoosterIllusion** [comment]
![image](https://user-images.githubusercontent.com/45019142/51427750-eb7cb480-1bc0-11e9-94c5-d948c34fb95f.png)

![image](https://user-images.githubusercontent.com/45019142/51427763-064f2900-1bc1-11e9-8a6c-78810f098671.png)

Could be a  version only for pro. I picked it up doing a repair install using the media creation tool having previously had .168, windows update wasn't offering the update at the time.

**Comment by JigSawFr** [comment]
I've exactly the same version, not supported.

**Comment by binarymaster** [comment]
No need to spam the issue with comments like that.

The problem is known and the ticket is open. You'll have to wait.

**Comment by JigSawFr** [comment]
> No need to spam the issue with comments like that.
> 
> The problem is known and the ticket is open. You'll have to wait.

I do not wanted to spam this issue, but just confirm that release exist too on our side. :)

**Comment by DarkSector** [comment]
Confirmed, .ini snippet provided by @RoosterIllusion works on v10.0.17763.292. Issue can be closed. Multiple concurrent connections allowed 
<img width="407" alt="screen shot 2019-01-22 at 4 04 34 pm" src="https://user-images.githubusercontent.com/315179/51573757-7b3f8e80-1e5f-11e9-91bf-4485775ffd11.png">

(Reboot required after .ini file is updated)

**Comment by devsk** [comment]
How do we use this ini file? I don't see any such thing in the distributed ZIP.

**Comment by DarkSector** [comment]
@devsk add the snippet to the end of the .ini file and leave one blank line in the end.

**Comment by binarymaster** [comment]
> Issue can be closed. 

@DarkSector no it can't, until the support is officially added.

**Comment by m333w** [comment]
Hi all,

I have change the offset like @RoosterIllusion but i cant login with multiple session. Here is a capture of my problem : https://imgur.com/a/5ntaj4N

How i can solve my problem, please ?

**Comment by DarkSector** [comment]
> > Issue can be closed.
> 
> @DarkSector no it can't, until the support is officially added.

My bad, sorry.

**Comment by tibidi** [comment]
It does not work for my 32bit version with this version.

**Comment by dcbasso** [comment]
I really sorry to ask that, but I download the file "https://github.com/stascorp/rdpwrap/blob/master/res/rdpwrap.ini" and put in the unzip RDPwrap folder.
At the end of file I put the @RoosterIllusion code...
I install, update and etc... reboot and nothing fix the problem, still showing "[not supported]"...

What Im doing wrong?

**Comment by strarsis** [comment]
@dcbasso: I am also trying to find the `rdpwrap.ini` file in order to add the lines above.
I found these instructions for editing the `rdpwrap.ini` file: https://github.com/stascorp/rdpwrap/issues/606#issuecomment-453752319

Edit: Other approach:
https://github.com/stascorp/rdpwrap/issues/347#issuecomment-382703119

Edit: Installer log:
````
[+] Folder created: C:\Program Files\RDP Wrapper\
[+] Current INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
````

So the `rdpwrap.ini` file is located under `C:\Program Files\RDP Wrapper\rdpwrap.ini`.

Edit: So the goal is to update the ini filed used by RDP Wrapper.
I achieved this by using the [second approach](https://github.com/stascorp/rdpwrap/issues/347#issuecomment-382703119) and it works now ([fully supported]).

**Comment by OSAdministrator** [comment]
Thanks for this fix, i added the snips ad instructed to the ini file and everything lit up!
![rdpwrapper-screenshot](https://user-images.githubusercontent.com/46981567/51647404-42c4b100-1f42-11e9-8007-0ef10f41526d.PNG)

**Comment by dcbasso** [comment]
Thanks @strarsis! appears to be fix! Very easy...

**Comment by dcbasso** [comment]
Appears "full supported" but when the second user try to access the remote desktop the server try to logout the first user.

How to fix it?

**Comment by m333w** [comment]
̷@̷O̷S̷A̷d̷m̷i̷n̷i̷s̷t̷r̷a̷t̷o̷r̷ ̷H̷i̷,̷ ̷
̷C̷a̷n̷ ̷y̷o̷u̷ ̷s̷e̷n̷d̷ ̷y̷o̷u̷r̷ ̷r̷d̷p̷w̷r̷a̷p̷.̷i̷n̷i̷ ̷f̷i̷l̷e̷ ̷p̷l̷e̷a̷s̷e̷ ̷?̷ ̷
̷
̷I̷ ̷h̷a̷v̷e̷n̷t̷ ̷s̷o̷l̷v̷e̷ ̷m̷y̷ ̷p̷r̷o̷b̷l̷e̷m̷ ̷(̷s̷c̷r̷o̷l̷l̷ ̷u̷p̷)̷ ̷s̷o̷ ̷i̷ ̷h̷a̷v̷e̷ ̷r̷e̷i̷n̷s̷t̷a̷l̷l̷ ̷a̷l̷l̷,̷ ̷b̷u̷t̷ ̷i̷ ̷n̷e̷e̷d̷ ̷t̷o̷ ̷e̷d̷i̷t̷ ̷t̷h̷e̷ ̷i̷n̷i̷ ̷w̷i̷t̷h̷ ̷t̷h̷e̷ ̷c̷o̷r̷r̷e̷c̷t̷ ̷i̷n̷f̷o̷r̷m̷a̷t̷i̷o̷n̷.̷
̷
̷B̷e̷s̷t̷ ̷r̷e̷g̷a̷r̷d̷s̷.̷

Edit: Woops i whas missing a line sorry for that...

Best regards.

**Comment by Igoricius** [comment]
Hello to everybody. I updated rdpwrap.ini and everything looks perfect 

![image](https://user-images.githubusercontent.com/47040465/51767702-79373300-20de-11e9-8ffd-60cfca1c1090.png)

but when I try to connect from another computer, I still have message "Another user is signed in...etc" Please, do you have any sugestion?

**Comment by joebeem** [comment]
Thanks for posting the solution to this issue.

I can confirm adding the snippets to the ini also worked for me on 10.0.17763.292.

Not sure if it was necessary to run the following exe commands, but I did this before modifying the ini.

rdpwinst.exe -u
rdpwinst.exe -i

After that,  run cmd  "net stop termservice", edit the ini to include snippets, and finally "net start termservice".

**Comment by Igoricius** [comment]
Thank you  @joebeem for sharing your experience, but even that didn't helped me. I tried several times, even with fresh installation, but problem is still the same.
Configuration seems to be OK, but problem exists, as you can see in screenshots below.
I will be grateful for any help...

![image](https://user-images.githubusercontent.com/47040465/51798608-a2a6aa80-2215-11e9-9097-13ca5e56c6ce.png)


![image](https://user-images.githubusercontent.com/47040465/51798603-902c7100-2215-11e9-82aa-482a3d2b8144.png)

**Comment by vmc88** [comment]
Same as above happened to me.

Fixed on restart.

**Comment by Maverick494** [comment]
This didn't work for me, even with restarting.  I added the snippets to the .ini and I still get Not Listening.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/ZzDwy1b/Broken-RDPWrapper.jpg" alt="Broken-RDPWrapper" border="0"></a><br />

What else do I need to check?

**Comment by rogerhanzhao** [comment]
same issue from me , how to fix it ?  I think , one week ago , it was working!

**Comment by ditchmagnet** [comment]
Here is my rdpwrap.ini.  This is working, just download and extract to your desktop. Follow these steps:

1. Open CMD as Administrator
2. net stop termservice
3. Backup your rdpwrap.ini
4. Copy and overwrite with my rdpwrap.ini (C:\Program Files\RDP Wrapper)
5. Go back to the CMD Admin - net start termservice
6. Check with RDPconf
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/2803354/rdpwrap.zip)

**Comment by jlipovac85** [comment]
Hello :)  I updated rdpwrap.ini and everything looks perfect
![image](https://user-images.githubusercontent.com/47112438/51845019-fb11a100-2316-11e9-9f7a-52d1b491ab5b.png)

but when I try to connect from another computer, I still have message "Another user is signed in...etc" Please, do you have any sugestion?

**Comment by ditchmagnet** [comment]
Does the problem go away when you uncheck "Single session per user" and "Apply"?  What version of Windows are you on? 8.1? Server 2012?

**Comment by jlipovac85** [comment]
the problem is still the same
![image](https://user-images.githubusercontent.com/47112438/51853577-ec33ea00-2328-11e9-924f-57b772a20216.png)
Windows version: 
![image](https://user-images.githubusercontent.com/47112438/51853604-f9e96f80-2328-11e9-9e19-2a2a3a025025.png)

**Comment by Igoricius** [comment]
It finally works!!! Thank you @ditchmagnet , your rdpwrap.ini was the solution. Please, explain us what is different in your configuration, because I used offsets @RoosterIllusion posted, but with no success.
Respect!

**Comment by Igoricius** [comment]
@jlipovac85 your OS version is not *292

**Comment by GitHub808user** [comment]
i'm getting what @Maverick494 is getting, the listener isn't listening. Same result when i append to the ini file or downloading the ini file that @ditchmagnet found. Tried restarting the termservice and reboot of the machine, nothing helps. Any ideas? I've verified that my dll file is on version 292

**Comment by RoosterIllusion** [comment]
Do you guys have x86 windows?  I have x64, so never tested x86.  I don't know if anyone tested x86.

**Comment by jlipovac85** [comment]
Today everything works. The KB4476976 update was installed
RDPWRAP finally works

**Comment by a-skv** [comment]
windows 10 ver. 1809 build 17763.292
all done according to manuals
edited .ini
windows after reboot
RDPConf - all became green
Connecting by second user - "The number of connections to this computer is limited..."

upd
used .ini posted by @ditchmagnet - works

**Comment by jonasburneika** [comment]
@a-skv can you clarify witch Win10 version do you have? Pro or Home?  Win10 Pro 1809 (OS Build 17763.292) and in my RDP folder .dll is not created :(

**Comment by arni7** [comment]
Welcome
strange thing after adding the entry from the first post
![image](https://user-images.githubusercontent.com/47143787/51906245-0242b880-23c4-11e9-8825-7c6e378d450f.png)

but printing works, after adding the @ditchmagnet file, everything works fine except printing
Please, do you have any sugestion?

**Comment by mixer-dm** [comment]
Hello.

I am simply not able to make it function. I have win 10 pro 17763.292 and everything is green as it should be. I installed the ini file following way. In the install folder i have the ini file prepared before typing rdowinst -i.
Everything is acitvated, i checked the ini file in the installation folder, it is the right modified one.
When i try to connect it disconnects the local user (lets call him user A) and the screen of the local user changes to the account i have connected to (user B).
I dont even get the message that someone will be disconected or that there are too many users. It simply disconnects user A.
It would be grateful for any suggestion.

PS: It acts like teamviewer

**Comment by ditchmagnet** [comment]
@mixer-dm sounds like it's working normally. You don't want to log out the current user? Did you uncheck "Single session per user" and "Apply"?

**Comment by mixer-dm** [comment]
Single session per user is unchecked, everything looks good (full green). Version is good. Account "user A" is logged. When account "user B" connects via remote desktop the screen of the logged "user A" turns to account "user B". Like Teamviewer. So both users (A+B) share one account.

After a clean new install of rdpwrapper i followed the instructions. Admin CMD, stop termservice, replace ini, start termservice, restarted windows unchecked "singe session per user" and still only one user possible. 

Does the dll file also need to be updated sonehow ?

PS: Do i need to turn off windows defender while configuring everything ?

**Comment by ditchmagnet** [comment]
I don't think you need to update the dll, but here is the one from my RDP Wrapper installation folder.  Single session and multiple session works fine for me. I think I did turn off defender (real time protection) during install since chrome was blocking it, I didn't want to risk it.  So maybe do that and uninstall/reinstall rdp wrapper completely.

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/2809588/rdpwrap.zip)

**Comment by mixer-dm** [comment]
Works great, thank you :)
I tried it on another computer (windows 10 installation with the same windows build version as the first computer) and it works.
I ll simply reinstall windows on the first computer and i am sure it ll work.
Thank you once again :)

PS: It worked instantly on the other ciomputer. Without any problem.

**Comment by Maverick494** [comment]
still have not listening.  I am using ditch's ini and dll.  I have rebooted, reinstalled, etc.

>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFC6B180000
SvcMain:    termsrv.dll+0x000000000002BFE0
SvcGlobals: termsrv.dll+0x000000000002C870
Version:    10.0.17763.292
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFC6B26CAB4] bServerSku = 1
SLInit [0x00007FFC6B26CAC4] bRemoteConnAllowed = 1
SLInit [0x00007FFC6B26CAD0] bFUSEnabled = 1
SLInit [0x00007FFC6B26CAC0] bAppServerAllowed = 1
SLInit [0x00007FFC6B26CAC8] bMultimonAllowed = 1
SLInit [0x00007FFC6B26CAB8] lMaxUserSessions = 0
SLInit [0x00007FFC6B26CACC] ulMaxDebugSessions = 0
SLInit [0x00007FFC6B26CAB0] bInitialized = 1
<<< CSLQuery::Initialize

that is the very last entry in the rdpwrap.txt

I can't think of anything else to do to get it to listen.  If I have to I guess I can try and get a pro upgrade for cheap somewhere and see if Win10 Pro is easier to get this working.
