### ISSUE TITLE
Terminal Server not supported 19318

### ISSUE THREAD

**Issue by romeroayub** [stascorp/rdpwrap#731]
Hello,

I try to install Wrapper in my server but appear msg Terminal Server not supported 19318

See attachement.

how i fix this ?

![photo_2019-04-10_21-23-01](https://user-images.githubusercontent.com/49501817/55922414-5db8d000-5bd7-11e9-9fa0-0971000276c2.jpg)

**Comment by fre4kyC0de** [comment]
Add these offsets to your rdpwrap.ini:
https://github.com/fre4kyC0de/rdpwrap/blob/master/6.3.9600.19318.txt

**Comment by romeroayub** [comment]
> Add these offsets to your rdpwrap.ini:
> https://github.com/fre4kyC0de/rdpwrap/blob/master/6.3.9600.19318.txt

is fixed! tsk! :D

**Comment by dotzero5** [comment]
> Add these offsets to your rdpwrap.ini:
> https://github.com/fre4kyC0de/rdpwrap/blob/master/6.3.9600.19318.txt

Hi. I have same issue. I added these offsets to rdpwrap.ini in installation folder and install it with -i key. But it still doesn't work (. I have x64 system.
