### ISSUE TITLE
Support for release 14393.3383

### ISSUE THREAD

**Issue by Prakhov** [stascorp/rdpwrap#939]
Windows 10.0.14393.3383
Need help!

**Comment by fre4kyC0de** [comment]
Done
https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt

**Comment by juliomgm** [comment]
![rdp](https://user-images.githubusercontent.com/34062888/70722871-e8664780-1cef-11ea-92a9-974ca25597a7.png)

Is is supported but it still doesn't work. Can anyone help?

**Comment by Prakhov** [comment]
Works like a charm! Thanks a lot.

**Comment by juliomgm** [comment]
After some restarts it is now working. Thanks.

**Comment by chankivhin** [comment]
need help ..!  version 1607 OS Build 14393.3384 RDP cannot work
thx for solution

**Comment by chankivhin** [comment]
![rdpwrap](https://user-images.githubusercontent.com/54789594/70731839-fa6cd800-1d39-11ea-8ea7-a89410368152.PNG)

**Comment by fre4kyC0de** [comment]
This is typical, if you forgot the blank line at the end of rdpwrap.ini.
Did you add one?

**Comment by sfg1234** [comment]
Hello, add https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt to ini file. At RdpConf it's fine, but in fact didn't help

**Comment by Prakhov** [comment]
> Hello, add https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt to ini file. At RdpConf it's fine, but in fact didn't help

I am adding not hole text in one place. I am splitting text in two sections and adding each section to corresponding section of the file. May be I am wrong but it works for me.

**Comment by wagner2020** [comment]
> > Hello, add https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt to ini file. At RdpConf it's fine, but in fact didn't help
> 
> I am adding not hole text in one place. I am splitting text in two sections and adding each section to corresponding section of the file. May be I am wrong but it works for me.

Please send your file for me !!

**Comment by sfg1234** [comment]
> > Hello, add https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt to ini file. At RdpConf it's fine, but in fact didn't help
> 
> I am adding not hole text in one place. I am splitting text in two sections and adding each section to corresponding section of the file. May be I am wrong but it works for me.

Did the same and restart PC, it helps thank you. Maybe needed only restart PC, not sure.
